# Generated by Django 5.2.3 on 2025-07-16 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_employes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='approval_status',
            field=models.CharField(choices=[('pending', 'En attente'), ('approved', 'Approuvé'), ('rejected', 'Rejeté')], default='pending', max_length=20, null=True, blank=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='statut',
            field=models.CharField(choices=[('actif', 'Actif'), ('inactif', 'Inactif'), ('conge', 'Congé'), ('en_attente', 'En attente d\'approbation')], default='en_attente', max_length=20, null=True, blank=True),
        ),
    ]
