# Generated by Django 5.2.3 on 2025-07-16 15:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_employes', '0002_auto_20250716_1618'),
    ]

    operations = [
        migrations.RunPython(
            code=lambda apps, schema_editor: apps.get_model('gestion_employes', 'Profile').objects.all().update(role=None),
            reverse_code=lambda apps, schema_editor: None
        ),
    ]
