# Generated by Django 5.2.3 on 2025-07-22 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_employes', '0003_auto_20250716_1633'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='nom_entreprise',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name="Nom de l'entreprise"),
        ),
    ]
