# Generated by Django 5.2.3 on 2025-07-31 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('gestion_employes', '0003_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='otp_required',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='two_factor_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='role',
            name='description',
            field=models.TextField(blank=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='role',
            name='nom',
            field=models.CharField(choices=[('superadmin', 'Super Administrateur'), ('DIRECTEUR_IT', 'Directeur IT'), ('RECEPTIONNISTE', 'Réceptionniste')], max_length=30, unique=True, verbose_name='Nom du rôle'),
        ),
        migrations.RemoveField(
            model_name='role',
            name='permissions',
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
        migrations.AddField(
            model_name='role',
            name='permissions',
            field=models.ManyToManyField(blank=True, to='auth.permission', verbose_name='Permissions liées'),
        ),
    ]
