# Generated by Django 5.2.3 on 2025-07-31 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_employes', '0004_profile_otp_required_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='nom',
            field=models.CharField(choices=[('superadmin', 'Super Administrateur'), ('DIRECTEUR_IT', 'Directeur IT'), ('RECEPTIONNISTE', 'Réceptionniste'), ('EMPLOYE', 'Employé')], max_length=30, unique=True, verbose_name='Nom du rôle'),
        ),
    ]
